site_name: fromitive's blog
site_url: https://fromitive.github.io/fromitive-blog
site_author: fromitive
site_description: >-
  본질과 핵심을 기록할수록 성장한다.

nav:
  - Home : index.md
  - Security: security.md
  - Project : project.md
  - Archive : archive.md
  - Coding Interview : coding-interview.md
  - CS : cs.md
  - Tips: tips.md

theme:
  name: material
  custom_dir : override
  icon:
    logo : material/shark
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate 
      toggle:
        icon: material/brightness-3
        name: Switch to light mode    
      primary: teal
      accent: teal
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

plugins:
  - rss:
      match_path: ".*"
      max_items: 2
      enabled: true
      abstract_chars_count: 160
      date_from_meta:
        key: "date"
        default: "2025-01-01 00:00:00"

  - social:
      cards_layout_options:
        font_family: Noto Sans KR
        background_color: "#6096B4"
        color: "#FFFFFF"

  - search:
      lang:
        - en
        - ko
  - blogging:
      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      categories:
        - name: security
          dirs:
            - security
          paging: true
          size : 3
          show_total : true

        - name: project
          dirs:
            - project
          paging: true
          size : 3
          show_total : true

        - name: archive
          dirs: 
            - archive
          paging: true
          size: 5
          show_total : true

        - name: coding-interview
          dirs:
            - coding-interview
          paging: true
          size : 3
          show_total : true
          
        - name: cs
          dirs:
            - cs
          paging: true
          size : 3
          show_total : true

        - name: tips
          dirs:
            - tips
          paging: true
          size : 3
          show_total : true

      # GLOBAL CONFIG: configs apply to all categories
      time_format: '%Y-%m-%d %H:%M'
      meta_time_format: '%Y-%m-%d %H:%M:%S'
      features:
        tags:
          index_page: tags.md
          insert: bottom
        
      locale: ko_KR



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
## google analytics
extra:
  analytics:
    provider: google
    property: G-Y55B987JCP

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fromitive
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%EB%AC%B4%EC%86%A1-%EC%9D%B4-7b6b681b9/

copyright: |
  &copy; 2025 <a href="https://github.com/fromitive"  target="_blank" rel="noopener">이무송</a>